name: 'CI/CD and manual prod deployments using ssh+github'
description: 'This will run deployment to stage server on every push to master and contains a manual workflow for deploying to production.'
author: 'Patrik Grinsvall'
inputs:
  STAGE_SSH_HOST:
    description: 'ssh host'
    required: true
  STAGE_SSH_PORT:
    description: 'ssh port'
    required: true
    default: 22
  STAGE_SSH_PRIVATE_KEY:
    description: 'private key in NOT IN OPENSSH FORMAT but in RSA PRIVATE KEY format.'
    required: true
  STAGE_SSH_USER:
     description: 'SSH user to connect to the stage server with'
     required: true
  STAGE_REPO_PATH:
    description: 'The path on server to update'
    required: true
  PROD_SSH_PRIVATE_KEY:
    description: 'the private key'
    required: false
  PROD_SSH_HOST:
    description: 'the host'
    required: false
  PROD_SSH_PORT:
    description: 'port if other than 22'
    required: false
    default: '22'
  PROD_SSH_USER:
    description: 'the user the private key belongs to'
    required: false
  PROD_REPO_PATH:
    required: false
    description: 'the path to the repo'
  env:
    STAGE_SSH_KEY: "${{ inputs.STAGE_SSH_PRIVATE_KEY }}"
    STAGE_SSH_HOST: "${{ inputs.STAGE_SSH_HOST }}"
    STAGE_SSH_PORT: "${{ inputs.STAGE_SSH_PORT }}"
    STAGE_SSH_USER: "${{ inputs.STAGE_SSH_USER }}"
    STAGE_REMOTE_PATH: "${{ inputs.STAGE_REPO_PATH }}"
    PROD_SSH_KEY: "${{ inputs.PROD_SSH_PRIVATE_KEY }}"
    PROD_SSH_HOST: "${{ inputs.PROD_SSH_HOST }}"
    PROD_SSH_PORT: "${{ inputs.PROD_SSH_PORT }}"
    PROD_SSH_USER: "${{ inputs.PROD_SSH_USER }}"
    PROD_REMOTE_PATH: "${{ inputs.PROD_REPO_PATH }}" 
  runs:
    using: "composite"
    steps:
      - id: deploystage
        run: |
            mkdir -p ~/.ssh
            echo "$STAGE_SSH_KEY" > ~/.ssh/stage_id_rsa
            sudo chmod 600 ~/.ssh/stage_id_rsa
            chmod 600 ~/.ssh/stage_id_rsa
            echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
            chmod 700 ~/.ssh
            chmod 600 ~/.ssh/stage_id_rsa
            ssh -i ~/.ssh/stage_id_rsa -o StrictHostKeyChecking=no -p $STAGE_SSH_PORT $STAGE_SSH_USER@$STAGE_SSH_HOST "cd $STAGE_REMOTE_PATH && ls -al"
     - id: deployprod
       run: |
        echo "start on prod"
        if [ "${{ github.event.inputs.deployprod }}" != "YES" ]; then echo "Not running prod" && exit; fi;

